version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3020:3020"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=production
      - HOST=reader.sharkovv.ru
