version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-reading_app}
      POSTGRES_USER: ${DB_USER:-reading_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_me}
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  api:
    build:
      context: ..
      dockerfile: ./Dockerfile
    environment:
      PORT: ${PORT:-3010}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-reading_app}
      DB_USER: ${DB_USER:-reading_user}
      DB_PASSWORD: ${DB_PASSWORD:-change_me}
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-replace_me}
      JWT_SECRET: ${JWT_SECRET:-replace_me}
      JWT_TTL_DAYS: ${JWT_TTL_DAYS:-7}
      DEFAULT_TZ: ${DEFAULT_TZ:-Europe/Samara}
    depends_on: [postgres]
    ports: ["${PORT:-3010}:${PORT:-3010}"]

  directus:
    image: directus/directus:latest
    restart: unless-stopped
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: 'pg'
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WEBSOCKETS_ENABLED: 'true'
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL:-http://localhost:8055}
    ports:
      - "8055:8055"
    depends_on:
      - postgres
    volumes:
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions

volumes:
  pgdata:
  directus_uploads:
  directus_extensions:
